import { Header } from '@/components/Header'
import '../styles/globals.scss'
import { Roboto } from 'next/font/google'
import { ReactNode } from 'react'

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR" className={roboto.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
